name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        run: |
          sudo apt-get update
          sudo apt-get install python3.10
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
          python3 --version

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
